### ISSUE TITLE
paz.sh

### ISSUE THREAD

**Issue by tomgco** [yldio/paz#14]
Currently the website `paz.sh` is still an email capture with a few descriptions about paz, will this be open-sourced so we can update the site with more up to date details and documentation? =D

**Comment by jongold** [comment]
Absolutely. I propose we figure out roughly what content we want on the site in the next few months, I'll build the first pass on it and then open source it so anyone can update it.

Can either plan content on here or in the pub ヽ(。_°)ノ

**Comment by lukebond** [comment]
Yes good point, thanks guys.

Perhaps this is a good place to determine what that is. And you remind me that I need to email all those people...if any of you are reading this, sorry :)

For me, I think the landing page needs to contain the following:
* Screenshots and a screencast
* List of features
* Links to documentation and repositories
* Links to talks/slides/etc. about Paz

Anything I've forgotten?

**Comment by sublimino** [comment]
prominently featured "try it now" minimum-friction walkthrough?

**Comment by tomgco** [comment]
> Screenshots and a screencast
> List of features
> Links to documentation and repositories
> Links to talks/slides/etc. about Paz

All sound good to me, especially like the “Try it now” / UI Demo.

Also one thing that I am finding difficult to decide is what to work on next / what needs to be done before we can call paz “Stable”, maybe this would suit well some place on the site or in the Contributing.md file. I specifically like the https://www.consul.io site.

**Comment by jongold** [comment]
For the demo - I wonder if we can rig up a version of the web UI with Ember fixtures to play around with?

**Comment by tomgco** [comment]
@jongold Sounds great.

**Comment by jongold** [comment]
First pass:
- Copy is all placeholder
- Header graphic is WIP
- Think it's a bit heavy on the krazy gradients; working on that
- Working on typography - not sure if it's too light, and whether to style headlines like 'Components' or 'Contributors' (i.e. gradients or not) 
- Not sure I've got all of the contributors since The Great Rebase Of 2015.

… but I think this is starting to get there.

- [ ] Have we got a roadmap I can use?
- [ ] Where's the best place to find documentation?
- [ ] Need to figure out which 'getting started' instructions to use.

![desktop hd](https://cloud.githubusercontent.com/assets/591643/6420292/c79217d2-bebc-11e4-8f06-ed521ac264fa.png)

**Comment by lukebond** [comment]
wow @jongold that looks absolutely beautiful :) thanks so so much

**Comment by lukebond** [comment]
@jongold roadmap not solidified but discussion can be found here: #19

**Comment by lukebond** [comment]
I think we should make a stop-gap fix to the landing page, maybe just removing all copy except the logo and "Website coming soon", and a link or two.

**Comment by jongold** [comment]
Why not just point the domain to this repo for the meantime?



—Jon Gold+447722118382

@jongold 

--------------------------------------------

Q: Why is this email three sentences or less?

A: http://three.sentenc.es

**Comment by jongold** [comment]
(I agree btw - don't think I'll have this design coded until the end of the weekend at the earliest)



—Jon Gold+447722118382

@jongold 

--------------------------------------------

Q: Why is this email three sentences or less?

A: http://three.sentenc.es

**Comment by lukebond** [comment]
Don't really want to redirect it to GH. Might just change that "coming soon" message and leave it at that for now. Would you object @jongold?

**Comment by jongold** [comment]
Go for it! 



—Jon Gold+447722118382

@jongold 

--------------------------------------------

Q: Why is this email three sentences or less?

A: http://three.sentenc.es

**Comment by lukebond** [comment]
Done. I apologise for my front-end skills.

**Comment by lukebond** [comment]
Just found the paz-landingpage repository, will move it to yldio and make it public and we can take it from there.

**Comment by tomgco** [comment]
@jongold Looks awesome =D

**Comment by jongold** [comment]
Weekend progress on front end - https://github.com/yldio/paz-landingpage/tree/v2

![paz - continuous deployment for production environments](https://cloud.githubusercontent.com/assets/591643/6434087/af61feee-c078-11e4-9733-29290a43ad30.png)

Couple of things left to do but I think it's basically shippable.

If someone wants to proofread it, I can merge. Was thinking we could just host it on GitHub Pages unless you particularly want to keep it Dockerized - but that might be over complicating things.

btw I created a new orphan branch in Git as it's essentially a new project; GitHub won't let me create a PR vs. current master but when I get the go-ahead I'll force push to master…

**Comment by lukebond** [comment]
Got for it, @jongold. Great stuff, thanks.

There are one or two minor copy tweaks I'll make after you merge.

**Comment by lukebond** [comment]
re Github pages, that would be fine normally but it would only work if Paz was it's own organisation I think? I think we will move it to its own organisation btw.

Landing page isn't Dockerised, perhaps you're thinking of paz-web.

**Comment by lukebond** [comment]
@jongold I created (https://github.com/paz-sh) and moved the landing page repo there

**Comment by jongold** [comment]
Moved from `paz-sh/landingpage` to `paz-sh/paz-sh.github.io`

Ready to go once you set up the DNS - just make a CNAME from `www.paz.sh` -> `paz-sh.github.io` https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/

**Comment by lukebond** [comment]
Thanks @jongold. I've done it, now we play the DNS propagation delay waiting game.

**Comment by tomgco** [comment]
Seems we are live shall we close this and move further discussion to: https://github.com/paz-sh/paz-sh.github.io/

**Comment by lukebond** [comment]
Yes, thanks all for this one.

**Comment by tomgco** [comment]
:heart: @jongold & all
