### ISSUE TITLE
Please add me to yldio/pazteam on quay.io - user: csabapalfi

### ISSUE THREAD

**Issue by csabapalfi** [yldio/paz#17]

**Comment by lukebond** [comment]
Hi @csabapalfi thanks for your interest in Paz! The repositories are actually open and the README was out of date. Let me know if you do have problems though.

**Comment by csabapalfi** [comment]
Thanks! :bow: Next time should check before blindly opening an issue. On the bright side the README is now up-to-date.

**Comment by lukebond** [comment]
The fault is entirely mine :)
