### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lukebond** [yldio/paz#19]
This is a place to discuss the short-to-medium term roadmap. Let's aim to distil it to a list of a handful of items that are doable in a month or two.

To get us started:
1. CLI
2. Monitoring with Heapster, InfluxDB and Grafana
3. Centralised logging
4. Something to observe what's running like Kubernetes' Replication Controller
5. Deployment history in the UI somewhere
6. Use Weave & WeaveDNS to simplify the complex HAProxy plumbing and service discovery
7. Proper test runner/framework (maybe Gulp)

**Comment by tomgco** [comment]
Awesome, Shall I create a milestone for each of these listed above.

Maybe it might even be worth creating some RFC's like rust-lang. https://github.com/rust-lang/rfcs/blob/master/text/0001-private-fields.md thoughts?

**Comment by lukebond** [comment]
@sublimino anything to add to a short-to-medium term roadmap?

Then yeah we can break them out into milestones and/or issues and discuss each separately. An RFC may make sense for some of them when that time comes.

**Comment by lukebond** [comment]
Adding another roadmap item:

1. CLI
2. Monitoring with Heapster, InfluxDB and Grafana
3. Centralised logging
4. Something to observe what's running like Kubernetes' Replication Controller
5. Deployment history in the UI somewhere
6. Use Weave & WeaveDNS to simplify the complex HAProxy plumbing and service discovery
7. Proper test runner/framework (maybe Gulp)
8. Move Paz to its own Github organisation

**Comment by tomgco** [comment]
> Something to observe what's running like Kubernetes' Replication Controller

Do we ever want to target kubernetes as a backend, if so then we could add this as a task?

**Comment by tomgco** [comment]
Also we need to find a way of improving the development (of paz) workflow, at the moment we rely on pulling the latest version from the registry to test within the cluster, we need some way (maybe within the cli) to assist in serving development versions of docker images without compromising the integrity of what is "Live" in the registry.

**Comment by lukebond** [comment]
I know we once agreed that this was a good idea going forward, but I'm reluctant to introduce the complexity of Kubernetes. One of Paz's strengths is its simplicity. I suspect that Weave/WeaveDNS could replace some of the HAProxy stuff and simplify it further. But I'm undecided.

We should rephrase item `6`, e.g.:
1. CLI
2. Monitoring with Heapster, InfluxDB and Grafana
3. Centralised logging
4. Something to observe what's running like Kubernetes' Replication Controller
5. Deployment history in the UI somewhere
6. Investigate simplifying, changing or replacing the Etcd/HAProxy service discovery layer (e.g. Weave, Kubernetes)- it's currently a bit brittle
7. Proper test runner/framework (maybe Gulp)
8. Move Paz to its own Github organisation

**Comment by sublimino** [comment]
- centralised logging ~= one-command cluster monitoring (i.e. `journal -f` on all units, got some fleet jiggerypokery to do this as there are silly TTY complications)
- test framework - strategy and coverage targets
- perhaps find one more person to [star the repo](https://www.dropbox.com/s/k6f1xb3d2c3jowi/Screenshot%202015-03-02%2013.01.53.png?dl=0) :D

**Comment by tomgco** [comment]
Another few for thought

- currently the user-data for digitalocean and vagrant share alot of the same logic but are split across multiple locations, maybe a build task / separation of units to create nicer user-data files. 
- unit files are in non intuitive folders see 1 & 2 in: https://github.com/yldio/paz/tree/master/unitfiles see about re-structuring the folder hierarchy.

**Comment by lukebond** [comment]
re unit file folders, I created #24 as I think it's more of an issue than something for the roadmap.

I'd like to have the CLI handle installation, in which case the user-data issues could come under that.

@sublimino your logging and testing items can be worked into the respective issues/milestones once they're created.

Is this a final list?
1. CLI (including installation)
2. Monitoring (e.g. with Heapster, InfluxDB and Grafana)
3. Centralised logging
4. Something to observe what's running like Kubernetes' Replication Controller (kill old versions and start new ones if missing)
5. Deployment history in the UI somewhere
6. Investigate simplifying, changing or replacing the Etcd/HAProxy service discovery layer (e.g. Weave, Kubernetes)- it's currently a bit brittle and difficult to understand / remember how it works
7. Proper test runner/framework (maybe Gulp), test strategy and coverage targets
8. Move Paz to its own Github organisation

**Comment by tomgco** [comment]
LGTM

**Comment by lukebond** [comment]
great, good discussion! let's divvy up into issues, discuss therein and milestone-ify.

**Comment by lukebond** [comment]
Created  #25, #26, #31, #32, paz/web#2, #33, #34 and #35.
