### ISSUE TITLE
paz-dnsmasq container not removed on failure

### ISSUE THREAD

**Issue by lukebond** [yldio/paz#22]
If `paz-dnsmasq` fails to start for whatever reason, or has previously stopped (e.g. reboot), it can't be restarted later because there is no `docker rm` in the unit file.

Fix incoming...

**Comment by tomgco** [comment]
Is this the `ExecStop=/usr/bin/docker rm -f paz-dnsmasq` command?

**Comment by lukebond** [comment]
Yes, and an `ExecStartPre=-...` just to be on the safe side. Have an untested fix at home.
